try:
    raise Exception('problem')
except Exception as e:
    print(e)